const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const ts=require("typescript");
function loadTs(file,dependencies={}){
 const module={exports:{}};
 const compiled=ts.transpileModule(fs.readFileSync(path.join(__dirname,"..",file),"utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
 new Function("require","module","exports",compiled)(name=>dependencies[name]??require(name),module,module.exports);
 return module.exports;
}
const model=loadTs("lib/model.ts"),analysis=loadTs("lib/analysis.ts");
const cache=loadTs("lib/cache.ts");
const upstream=loadTs("lib/upstream.ts",{"./request":loadTs("lib/request.ts"),"./cache":cache,"./model":model,"./champions.json":require("../lib/champions.json")});
const sample=require("../lib/seed.json");
const result=analysis.analyze(sample.rows);
assert.equal(result.wins,10);assert.equal(result.losses,1);
assert.ok(Math.abs(result.elo-1775.09090909)<1e-6);
assert.equal(result.max,2359);assert.equal(result.min,1238);
assert.equal(result.windows[5],2167);assert.equal(result.windows[10],1781.7);
assert.equal(result.windows[20],null);assert.equal(result.windows[30],null);
assert.ok(Math.abs(result.ema-1957.132626)<1e-5);
assert.ok(Math.abs(result.delta-770.6)<1e-7);
assert.equal(analysis.analyze([{...sample.rows[0],teamElo:null}]).elo,null);
assert.equal(analysis.analyze([{...sample.rows[0],mode:"KIWI"},sample.rows[1]]).elo,null);
assert.equal(analysis.analyze([]).winrate,null);
assert.equal(analysis.analyze([{...sample.rows[0],win:null}]).losses,0);
assert.throws(()=>model.validateQuery({player:"name",area:"艾欧尼亚",mode:"ranked",count:10}));
assert.throws(()=>model.validateQuery({player:"name#123",area:"艾欧尼亚",mode:"ranked",count:300}));
assert.throws(()=>model.validateQuery({player:"name#123",area:"__proto__",mode:"ranked",count:10}));
const m={gameId:"fixture",championId:"8",title:"单双- 用时30分5秒",isWin:2,titleTime:"08-15 12:00:00"};
const detail={data:{gameMode:"CLASSIC",teamDetails:[{teamId:"100",win:"Win",teamElo:2300},{teamId:"200",win:"Fail",teamElo:2209}],wgBattleDetailInfo:[{openIdNow:"target",teamId:"200",scoreInfo:"11/8/6",scoreInfoNum:10.6}]}};
const normalized=upstream.normalizeMatch(m,detail,"target","test#1");
assert.equal(normalized.teamElo,2209);assert.equal(normalized.opponentElo,2300);assert.equal(normalized.win,false);
assert.equal(normalized.duration,1805);
assert.equal(upstream.normalizeMatch(m,detail,"missing","other#1").teamElo,null);
const s=upstream.signature(new Date("2026-09-03T04:05:06Z"));
assert.deepEqual(s,{lzyumiSign:require("node:crypto").createHash("md5").update("dld09o03u12d05o06dld").digest("hex"),signStr:"93125633633"});
console.log("PASS: recorded sample statistics, missing and mixed-mode data, identity-to-team mapping, input validation, China-time signing.");

const ranks=loadTs("lib/elo-rank.ts");
assert.equal(ranks.eloRank(0),"黑铁Ⅳ");
assert.equal(ranks.eloRank(399.99),"黑铁Ⅰ");
assert.equal(ranks.eloRank(400),"青铜Ⅳ");
assert.equal(ranks.eloRank(1500),"黄金Ⅰ");
assert.equal(ranks.eloRank(1775.1),"铂金Ⅲ");
assert.equal(ranks.eloRank(2359),"翡翠Ⅰ");
assert.equal(ranks.eloRank(2400),"钻石Ⅳ");
assert.equal(ranks.eloRank(2799),"钻石Ⅰ");
assert.equal(ranks.eloRank(2800),"大师及以上");
assert.equal(ranks.eloRank(2963),"大师及以上");
assert.equal(ranks.eloRank(null),null);
assert.equal(ranks.eloRank(NaN),null);
assert.equal(ranks.eloRank(-1),null);
assert.equal(model.validateQuery({player:"test#123",area:"艾欧尼亚",mode:"mayhem",count:10}).mode,"mayhem");
assert.equal(model.MODES.mayhem.id,1);
assert.equal(model.isMayhemMatch({queue:"海斗"}),true);
assert.equal(model.isMayhemMatch({queue:"未知",mode:"KIWI"}),true);
assert.equal(model.isMayhemMatch({queue:"大乱斗",mode:"ARAM"}),false);
assert.equal(model.isMayhemMatch({queue:"单双",mode:"CLASSIC"}),false);
const mayhem=upstream.normalizeMatch({...m,title:"海斗(独闯天涯)- 用时15分47秒"},{data:{gameMode:"KIWI",teamDetails:[{teamId:"200"}],wgBattleDetailInfo:detail.data.wgBattleDetailInfo}},"target","test#1");
assert.equal(mayhem.queue,"海克斯大乱斗");
assert.equal(mayhem.mode,"KIWI");
assert.equal(mayhem.teamElo,null);
console.log("PASS: source ELO table boundaries and mayhem separation.");
